[providers]
python = "3.11"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.build]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[phases.start]
cmd = "python main.py" 